# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cross_fspatial_weights <- function(indices, distances, feature_mat1, feature_mat2, nels, sigma, fsigma, alpha, binary) {
    .Call('neighborweights_cross_fspatial_weights', PACKAGE = 'neighborweights', indices, distances, feature_mat1, feature_mat2, nels, sigma, fsigma, alpha, binary)
}

fspatial_weights <- function(indices, distances, feature_mat, nels, sigma, fsigma, alpha, binary) {
    .Call('neighborweights_fspatial_weights', PACKAGE = 'neighborweights', indices, distances, feature_mat, nels, sigma, fsigma, alpha, binary)
}

spatial_weights <- function(indices, distances, nels, sigma, binary) {
    .Call('neighborweights_spatial_weights', PACKAGE = 'neighborweights', indices, distances, nels, sigma, binary)
}

